### ISSUE TITLE
Update symbols when symbols source file changes.

### ISSUE THREAD

**Issue by sallomendo** [kmerc/sketch-import-symbols#1]
First of all thank you for this plugin :)

In my workflow I have multiple sketch with symbols in it that I want to import. The problem I found is when I update one file and want to import it again it doesn't update the current symbols.

Probably this is a sketch limitation and want to let you know.

Thanks.

**Comment by kmerc** [comment]
Hi @simiographics,

Currently the plugin doesn't 'watch' a linked / external sketch file for changes and reimport when it sees a change. 

Thanks for the feedback though!
