### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by amplexity** [kmerc/sketch-import-symbols#2]
I can't tell you why, but it doesn't work for me. 
When I go to 'Plugins' and select the 'Import Symbols' it brings up finder. I select the sketchfile that contains all the symbols. Enter. But nothing happens. 

IOS 10.11.1
Sketch 3.4.2

**Comment by kmerc** [comment]
Hi @amplexity,

Can you please update to Sketch 3.4.3 and try again? Let me know how you get on.

Thanks.

**Comment by amplexity** [comment]
I updated from my App Store version to the latest (3.4.4) and now your plugin works PERFECTLY!! Love it. Thank you!

**Comment by kmerc** [comment]
Glad to hear it! I think there may have been some plugin related issue with that in-between version of Sketch for some reason. I'm happy you like it.

Thanks,
