### ISSUE TITLE
Any news on this? Not working in Sketch Version 41

### ISSUE THREAD

**Issue by arnoldstoba** [kmerc/sketch-import-symbols#8]
@kmerc not planning on updating this I guess? Sad, pretty great idea.

**Comment by kmerc** [comment]
Sketch 3.7 completely changed how Symbols worked - apologies that I have not had a chance yet to repair this. 

I'm just getting started on a new solution now. Watch this space ;)

**Comment by kmerc** [comment]
@arnoldstoba This is now resolved - the latest version resolves this issue!

**Comment by arnoldstoba** [comment]
Awesome stuff! Thanks a lot 👍
